### PR TITLE
Olson form update

### PR DESCRIPTION
**Pull request by tomdionesotes**
updating yaml to reflect https://olson.house.gov/contact/email-me

### CODE REVIEW

**Comment by kthayer424** [comment]
For optional fields, we should just set `required:false`. Something like address line 2 is always optional, but is important to fill out for people who need to use it.

**Comment by tomdionesotes** [comment]
i'll add the address2 line back in and set it as '<required:false>'

**Comment by kthayer424** [comment]
Cool, do it with prefix also, the extra data if it's available is useful for the targets when responding. 

In general, if we have a yaml variable for a piece of data, it should appear in the yaml if the target has that field on their form.

**Comment by tomdionesotes** [comment]
committed and pushed. thanks!

**Comment by kthayer424** [comment]
The prefix values also need to be included when in a drop down to ensure they are mapped correctly.

**Comment by kthayer424** [comment]
@tomdionesotes Looks good, if it's all tested, feel free to merge this.

**Comment by tomdionesotes** [comment]
yep, tested out in yamltron and it passes.

**Pull request merged**
