### PR TITLE
Federal-level updates

### PR DESCRIPTION
**Pull request by OdeclasV**
- Update Gov Sununu
- Pull Sec Mnuchin

### CODE REVIEW

**Comment by tomdionesotes** [comment]
I think you had already created a yaml for Kyl (`FAZS21684bf4`) yesterday FYI

**Comment by tomdionesotes** [comment]
you did merge the other PR to develop: https://github.com/NGPVAN/contact-congress/pull/647

you should merge the latest changes from the develop branch into your `federal-yamls-update` branch before doing anything else. there will be a single copy of the Kyl yaml.

**Comment by OdeclasV** [comment]
Awesome, just merged latest changes from develop into `federal-yamls-update`

**Comment by tomdionesotes** [comment]
Awesome! You can see in the diff now that the only changes resulting from this PR are Sununu and Mnuchin, so Kyl remains unchanged.

**Pull request merged**
