### PR TITLE
Create two new folders and move custom targets there

### PR DESCRIPTION
**Pull request by OdeclasV**
Folders created:

- regsgov: for all of the custom targets pointing to a regulations.gov forms. I'm taking those out of /notready to this folder. These are all old, nonactive custom targets.

- fedregister: for custom targets that use the heroku app to submit msgs via the federalregister api. 

Other than helping to organize these yamls better, the idea with these folders is to be able to have a place where to quickly access regs.gov or federalregister yamls for active custom targets. For instance, if we have an active custom target that needs to be edited to point to federalregister, I would create a copy of the active regs.gov target, store it in the regsgov folder, and edit said yaml to use the heroku app. I think this would help with quickly switching between one format to the other, which looks like something we might do more often in the foreseeable future. 

Let me know if you have any thoughts or advice about this @tomdionesotes

### CODE REVIEW

**Comment by tomdionesotes** [comment]
Yamltron only posts to targets in the members folder, so this would not work for active yamls for active targets. Otherwise it is a great idea for better organization of yamls used for previous regs.gov / fed register targets!

**Comment by OdeclasV** [comment]
yup! That's my bad on the description in my last comment, it's a little bit confusing. Let me try again: if we have an active custom target that points to a regs.gov form, I would create a copy of that yaml and save it in the regsgov folder as reference (and to keep said yaml in case we need to switch back to regs.gov). I would then make changes to the custom target in the members folder to point to the heroku app, so it's still getting called on by yamltron. Does this makes a little more sense?

**Comment by tomdionesotes** [comment]
It's your workflow, so if you find that helpful then go for it! I'd just want to be sure the copy of the yaml we save in the regsgov folder is: 
- updated if the yaml in the members folder needs to be tweaked, for an updated selector for example
- saved with a different file name so there's no confusion

**Comment by OdeclasV** [comment]
Noted, I'll make sure that happens when copying/moving/editing files in these folders. Thanks Tom!

**Pull request merged**
