### PR TITLE
Update senator's yaml

### PR DESCRIPTION
**Pull request by OdeclasV**
Sen Cornyn just revamped his form. Updating his yaml to account for that. 

PS- since Tom is leaving us 😿 , I'm adding Tommy here. Per Anna, Tommy will help review these PRs once Tom transitions to that other, less fun team.

### CODE REVIEW

**Comment by tirish** [comment]
**Branch Delete Police**
parrot cop
*Can this branch be deleted?*

**Comment by OdeclasV** [comment]
Omg Tom don't leave

**Comment by tirish** [comment]
> Tommy will help review these PRs once Tom transitions to that other, less fun team.
dear god

**Comment by tomdionesotes** [comment]
I leave 8/1!

**Pull request merged**
