### PR TITLE
VAN-72649: create custom yamls

### PR DESCRIPTION
**Pull request by OdeclasV**
Client requested same identical custom target in two different committees. Thus why both of these yamls are identical except for the bioguideIDs.

### CODE REVIEW

**Comment by OdeclasV** [comment]
@tomdionesotes @annanhan any thoughts/concerns about this before merging?

**Comment by tomdionesotes** [comment]
Do those waits need to be so high due to the slow regs.gov site?

**Comment by OdeclasV** [comment]
yeah, during heavy traffic the regs.gov form tend to slow down and cause more errors. The waits (which I do agree are alot) are there to make sure we get some successes even with heavy traffic.

**Comment by OdeclasV** [comment]
@tomdionesotes let me know if you have any more comments/concers

**Pull request merged**
